// defines event types
enum EVENT_TYPE
{
    SIMULATION_START,
    JOB_ARRIVAL,
    JOB_CPU_START,
    JOB_CPU_FINISH,
    JOB_DISK_0_START,
    JOB_DISK_0_FINISH,
    JOB_DISK_1_START,
    JOB_DISK_1_FINISH,
    JOB_EXIT,
    SIMULATION_END
};